# Dockerfile.flask
FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy model + Flask app
COPY improved_cnn_model.h5 .
COPY flaskapi.py .

EXPOSE 5000
CMD ["python", "flaskapi.py"]
