# Dockerfile.frontend
FROM node:22 AS build

WORKDIR /app
COPY frontend/package*.json ./frontend/
WORKDIR /app/frontend
RUN npm install

COPY frontend/ .
RUN npm run build

# --- Serve build with nginx ---
FROM nginx:stable-alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
